Vagrant.configure("2") do |config|
  
 
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.network "private_network", ip: "192.168.56.3"
  end
 
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.network "private_network", ip: "192.168.56.7"
    db01.vm.provision "shell", inline: <<-SHELL
	yum install mariadb-server -y
	systemctl start mariadb
	systemctl enable mariadb
	mysql -u root -e 'CREATE DATABASE breakitdown;'
	SHELL
  end
end
